### ISSUE TITLE
Can all this repo can be moved to LimeSurvey/LimeSurvey

### ISSUE THREAD

**Issue by Shnoulle** [LimeSurvey/ls3-question-objects-spec#18]
Can we move all plugin discussion on LimeSurvey/LimeSurvey ?
@c-schmitz  : can you fork it to LimeSurvey/LimeSurvey repo , or better @SamMousa can you transfer ownership

**Comment by SamMousa** [comment]
Yes I can, and I will as soon as @c-schmitz confirms :)

**Comment by c-schmitz** [comment]
Sure, move it over.

**Comment by SamMousa** [comment]
Hmm can only transfer it if I have admin rights and forming won't fork the issues afaik.

Leave it here for now since it is unofficial discussion anyway?

Or give me temporary admin rights or any other ideas?

**Comment by c-schmitz** [comment]
Try again, now.

**Comment by SamMousa** [comment]
It worked. You can reset my access if needed. I've given the LimeSurvey team access.

**Comment by Shnoulle** [comment]
@SamMousa : yes it's maybe unoficial : but it's LS core official future dev, no ?

This feature is closed ;)
